- name: Run "apt-get update"
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install missing packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - 'python-dev'
    - 'python-virtualenv'
    - 'virtualenvwrapper'
    - 'geoipupdate'
    - 'tor' 
    - 'redis-server'
