- name: Ensure .bashrc has proper exports
  blockinfile:
    dest: "/root/.bashrc"
    block: |
      export WORKON_HOME=/mnt/volume-nbg1-1/.virtualenvs
      source /usr/local/bin/virtualenvwrapper.sh
      export REDIS_SOCKET=/var/run/redis/redis-server.sock
    marker: '# {mark} ANSIBLE MANAGED BLOCK - virtualenv + redis'
    insertafter: EOF
    create: yes

- name: Ensure THP is disabled
  blockinfile:
    dest: "/etc/rc.local"
    block: |
      echo never > /sys/kernel/mm/transparent_hugepage/enabled
    marker: '# {mark} ANSIBLE MANAGED BLOCK - THP'
    insertafter: EOF
    create: yes
